### ISSUE TITLE
Please remove the testing data

### ISSUE THREAD

**Issue by dido48** [elections-contest/pe2013#10]
The testing data ~Tests/2/Candidates.txt~ includes my surname and therefore, I would like to be removed or changed

https://github.com/elections-contest/pe2013/blob/master/Tests/2/Candidates.txt

Thanks in Advance!

**Comment by RealEnder** [comment]
The file pointed is part of CEC's and REC's decisions and opendata for Parliamentary elections 2013, thus it's public data. There are only names, without additional identification info, so based on this the person can't be unique identified.
Also please do notice, even if we remove the name(which we can't currently know which is it exactly), the data will stay in git commitlogs.
