### ISSUE TITLE
Пресмятане на общ брой гласове

### ISSUE THREAD

**Issue by aquilax** [elections-contest/pe2013#3]
При положение че по Раздел II са разпределени мандати за независими кандидати и общия брой мандати е редуциран, гласовете за тези независими кандидати, влизат ли в общия брой на гласовете за Раздел III, чл.12 ?

**Comment by RealEnder** [comment]
чл. 12 гласи: "Пресмята се сумата от подадените действителни гласове от всички секции в страната и извън страната.". Независимите кандидати се избират също с действителни гласове, подадени в съответния район, съответно визат в общата сума.
