### ISSUE TITLE
Имплементации

### ISSUE THREAD

**Issue by aquilax** [elections-contest/pe2013#5]
Има ли смисъл от реализация на методологията на два различни програмни езика или да се концентрирам върху едно решение ?

**Comment by RealEnder** [comment]
В общите условия е записано:
"Един участник/отбор може да предложи само едно решение"
Аз лично мисля, че ще е полезно да се сравнят имплементациите на няколко езика, а и ако имаш два работещи алгоритъма, ще можеш да ги "сбиеш" и да прецениш кой се държи по-добре.
Разбира се, най-важно е да имаш поне едно работещо решение, а не две "до някъде". Документирането и визуализирането на алгоритъма също не трябва да се подценява.
Успех!
